### ISSUE TITLE
Tracking associations going both ways end up on same line

### ISSUE THREAD

**Issue by Averydevlin** [aid848/-410-Program-Analysis#15]

**Comment by aid848** [comment]
lines going to the same nodes but opposite directions show up as one line which could be confusing.
![image](https://user-images.githubusercontent.com/33972075/84466813-23a9ea80-ac2f-11ea-8d9f-f22fdb90ee5d.png)
![image](https://user-images.githubusercontent.com/33972075/84466820-29073500-ac2f-11ea-9c04-8651ea5afd6f.png)
![image](https://user-images.githubusercontent.com/33972075/84466833-315f7000-ac2f-11ea-8d34-e24f76c236ca.png)
