### ISSUE TITLE
Unconnected nodes float away on the front end display

### ISSUE THREAD

**Issue by aid848** [aid848/-410-Program-Analysis#5]

**Comment by aid848** [comment]
we could set the size of the javascript viewport based on the number of nodes

**Comment by aid848** [comment]
If all the nodes are linked somehow as they should since no calls or anything (would be dead code right?) the floating away problem might no be a thing anymore?

**Comment by SilentM** [comment]
Nodes no longer float away, they stick to borders but can be moved anytime

**Comment by SilentM** [comment]
I think this is solved now
